version: '3'
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kakaopaycoin
      MYSQL_USER: root

    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']


  coin-scatter-service:
    container_name: coin-scatter
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    ports:
      - 8888:8888
    restart: always
    links:
      - mysql
    depends_on:
      - mysql