version: '3'
services:
  mysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: kakaopaycoin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ~/store/mysql5.6:/var/lib/mysql
    ports:
      - "3306:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']