spring:
  profiles: prod

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          format_sql: true
      format_sql: true
      use_sql_comments: true
      id:
        new_generator_mappings: true

  datasource:
    url: jdbc:mysql://localhost:3306/kakaopaycoin?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8

