spring:
  profiles: dev

  jpa:
    database-platform: H2
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate:
          format_sql: true
      format_sql: true
      use_sql_comments: true
      id:
        new_generator_mappings: true

  datasource:
    platform: h2
    url: jdbc:h2:~/testdb?useUnicode=true&characterEncoding=utf8;MODE=mysql;
    #    url: jdbc:h2:mem:testdb;MODE=mysql;
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    username: sa  # 사용자 이름 (로그인 시 사용)

  h2:
    console:
      enabled: true  # H2 웹 콘솔을 사용하겠다는 의미

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8

