database: h2

spring:
  datasource:
    schema: classpath*:db/${database}/schema.sql
    data: classpath*:db/${database}/data.sql

  jpa:
    show_spl: true
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          format_sql: true
      format_sql: true
      use_sql_comments: true
      id:
        new_generator_mappings: true
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      springframework.web: debug

server:
  port: 8888
