--DROP TABLE scatter IF EXISTS;
--
--create table scatter (
--    id bigint generated by default as identity,
--    create_date timestamp,
--    modified_date timestamp,
--    email varchar(255) not null,
--    name varchar(255) not null,
--    picture varchar(255),
--    primary key (id)
--);

INSERT INTO SCATTERER(id, bonus_coin, each_coin, expire_date_time, head_count, receiver_count,  remain_coin, room_id, token, total_coin, user_no, create_at, update_at)  VALUES(	2, 1,	333,	 DATEADD(MINUTE, 10, current_timestamp) ,	3,	0,	1000,	'rrr',	'AfG',	1000,	111, current_timestamp, current_timestamp);

INSERT INTO SCATTERER(id, bonus_coin, each_coin, expire_date_time, head_count, receiver_count,  remain_coin, room_id, token, total_coin, user_no, create_at, update_at)  VALUES(	3, 0,	250,	 DATEADD(MINUTE, 10, current_timestamp) ,	4,	0,	1000,	'rrr',	'SeF',	1000,	222, current_timestamp, current_timestamp);
